### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by cyberixae** [duivvv/gulp-clipboard#2]
I'm using gulp-clipboard on Node.js v7.6.0

Requiring gulp-clipboard gives me the following warnings.
```
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
```

The warnings seem to go away if I modify gulp-clipboard to use the latest version of the `copy-paste` npm package.

**Comment by duivvv** [comment]
Will bump the dependency tomorrow. PR always welcome

**Comment by cyberixae** [comment]
I didn't think or test it thoroughly but it seemed that you have to also replace
```
	copy_paste = require("copy-paste").silent()
```
with
```
	copy = require("copy-paste").copy
```

**Comment by motmit** [comment]
Think this is what cyberixae is suggesting.

I'm using this with npm copy-paste v1.3.0 
then changed the index for this -
`copy_paste = require("copy-paste").silent()`
to
`copy_paste = require("copy-paste");`

and 
`copy(String(file.contents));`
to
`copy_paste.copy(String(file.contents));`

now working fine.

**Comment by duivvv** [comment]
PR always welcome
